### ISSUE TITLE
lightning_fabric.utilities.exceptions.MisconfigurationException: Unknown configuration for model optimizers.

### ISSUE THREAD

**Issue by blueridanus** [BlinkDL/RWKV-LM#251]
After following steps in the README, and when running `./demo-training-run.sh`:

```
[rank0]: Traceback (most recent call last):
[rank0]:   File "RWKV-LM/RWKV-v5/train.py", line 332, in <module>
[rank0]:     trainer.fit(model, data_loader)
[rank0]:   File ".venv/lib/python3.12/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
[rank0]:     call._call_and_handle_interrupt(
[rank0]:   File ".venv/lib/python3.12/site-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt
[rank0]:     return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".venv/lib/python3.12/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 88, in launch
[rank0]:     return function(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".venv/lib/python3.12/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
[rank0]:     self._run(model, ckpt_path=self.ckpt_path)
[rank0]:   File ".venv/lib/python3.12/site-packages/pytorch_lightning/trainer/trainer.py", line 1093, in _run
[rank0]:     self.strategy.setup(self)
[rank0]:   File ".venv/lib/python3.12/site-packages/pytorch_lightning/strategies/deepspeed.py", line 345, in setup
[rank0]:     self.init_deepspeed()
[rank0]:   File ".venv/lib/python3.12/site-packages/pytorch_lightning/strategies/deepspeed.py", line 456, in init_deepspeed
[rank0]:     self._initialize_deepspeed_train(model)
[rank0]:   File ".venv/lib/python3.12/site-packages/pytorch_lightning/strategies/deepspeed.py", line 489, in _initialize_deepspeed_train
[rank0]:     optimizer, lr_scheduler, _ = self._init_optimizers()
[rank0]:                                  ^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".venv/lib/python3.12/site-packages/pytorch_lightning/strategies/deepspeed.py", line 462, in _init_optimizers
[rank0]:     optimizers, lr_schedulers, optimizer_frequencies = _init_optimizers_and_lr_schedulers(self.lightning_module)
[rank0]:                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".venv/lib/python3.12/site-packages/pytorch_lightning/core/optimizer.py", line 188, in _init_optimizers_and_lr_schedulers
[rank0]:     optimizers, lr_schedulers, optimizer_frequencies, monitor = _configure_optimizers(optim_conf)
[rank0]:                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".venv/lib/python3.12/site-packages/pytorch_lightning/core/optimizer.py", line 251, in _configure_optimizers
[rank0]:     raise MisconfigurationException(
[rank0]: lightning_fabric.utilities.exceptions.MisconfigurationException: Unknown configuration for model optimizers. Output from `model.configure_optimizers()` should be one of:
[rank0]:  * `Optimizer`
[rank0]:  * [`Optimizer`]
[rank0]:  * ([`Optimizer`], [`LRScheduler`])
[rank0]:  * {"optimizer": `Optimizer`, (optional) "lr_scheduler": `LRScheduler`}
[rank0]:  * A list of the previously described dict format, with an optional "frequency" key (int)
```
Dependencies:
```
uv pip show pytorch-lightning deepspeed torch
Name: deepspeed
Version: 0.14.4
Location: .venv/lib/python3.12/site-packages
Requires: hjson, ninja, numpy, nvidia-ml-py, packaging, psutil, py-cpuinfo, pydantic, torch, tqdm
Required-by:
---
Name: pytorch-lightning
Version: 1.9.5
Location: .venv/lib/python3.12/site-packages
Requires: fsspec, lightning-utilities, numpy, packaging, pyyaml, torch, torchmetrics, tqdm, typing-extensions
Required-by:
---
Name: torch
Version: 2.4.0+cu124
Location: .venv/lib/python3.12/site-packages
Requires: filelock, fsspec, jinja2, networkx, nvidia-cublas-cu12, nvidia-cuda-cupti-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-runtime-cu12, nvidia-cudnn-cu12, nvidia-cufft-cu12, nvidia-curand-cu12, nvidia-cusolver-cu12, nvidia-cusparse-cu12, nvidia-nccl-cu12, nvidia-nvjitlink-cu12, nvidia-nvtx-cu12, setuptools, sympy, triton, typing-extensions
Required-by: deepspeed, pytorch-lightning, torchmetrics
```

**Comment by BlinkDL** [comment]
please share your ./demo-training-run.sh

**Comment by blueridanus** [comment]
fwiw it worked if I changed `configure_optimizers()` to return `{"optimizer": ...}`
