### ISSUE TITLE
跑rwkv_v6_demo.py报错

### ISSUE THREAD

**Issue by supercyt** [BlinkDL/RWKV-LM#256]
GPU：RTX 3080
Driver Version: 550.90.07 
CUDA：12.4

```Loading extension module wkv6...
Traceback (most recent call last):
  File "/autodl-fs/data/rwkv/RWKV-LM/RWKV-v5/rwkv_v6_demo.py", line 271, in <module>
    wkv6_cuda = load(name="wkv6", sources=["cuda/wkv6_op.cpp", f"cuda/wkv6_cuda.cu"],
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 1309, in load
    return _jit_compile(
           ^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 1745, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 2143, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 813, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1289, in create_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
ImportError: dynamic module does not define module export function (PyInit_wkv6)```

**Comment by BlinkDL** [comment]
试试最新torch 2.x

**Comment by supercyt** [comment]
> 试试最新torch 2.x
> 
> 另外 python 3.12 没试过，我用 3.10

切到python3.10还是有点问题，把 wkv6_op.cpp 这样改完之后可以跑了：
python3.12 torch 2.3.0
```
// TORCH_LIBRARY(wkv6, m) {
//     m.def("forward", forward);
//     m.def("backward", backward);
// }

PYBIND11_MODULE(wkv6, m) {
  m.def("forward", &forward, "LLTM forward");
  m.def("backward", &backward, "LLTM backward");
}
```
