### ISSUE TITLE
Add a requirements.txt?

### ISSUE THREAD

**Issue by richardklafter** [BlinkDL/RWKV-LM#37]
Ran into this issue while installing: 
```
python ./train.py --help                                                                                                                     
Traceback (most recent call last):                                                                                                                                                  
  File "/fast/RWKV-LM/RWKV-v4/./train.py", line 10, in <module>                                                                                                                     
    from src.binidx import MMapIndexedDataset                                                                                                                                       
  File "/fast/RWKV-LM/RWKV-v4/src/binidx.py", line 30, in <module>                                                                                                                  
    6: np.float,                                                                                                                                                                    
  File "/fast/RWKV-LM/venv/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__                                                                                
    raise AttributeError(__former_attrs__[attr])                                                                                                                                    
AttributeError: module 'numpy' has no attribute 'float'.                                                                                                                            
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you 
specifically wanted the numpy scalar type, use `np.float64` here.                                                                                                                   
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:                                                                
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?  
```
Root issue was because `np.float` was removed https://numpy.org/doc/stable/release/1.24.0-notes.html#expired-deprecations

Anyway, a requirements.txt with versions would be helpful. Unless I missed something?

**Comment by BlinkDL** [comment]
fixed :)

**Comment by richardklafter** [comment]
thx
